@API_HostAddress = http://localhost:5013

POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "phoneNumber": "89200000009",
  "name": "Артём",
  "gender": "Male",
  "relationShip": "Serious",
  "dateOfBirth": "2015-05-14",
  "description": "Тестовое описание",
  "city": "Москва"
}

###

POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "phoneNumber": "892000ва",
  "name": "1",
  "gender": "Female",
  "relationShip": "Serious",
  "dateOfBirth": "2001-05-15",
  "description": "Тестовое описание 2",
  "city": "Москва"
}

###

POST {{API_HostAddress}}/api/likes
Content-Type: application/json

{
  "fromUserId": "9a937bee-06f6-4f05-b486-6050965a105e",
  "toUserId": "cf82b549-ea1c-45db-b5da-04ec9135295d"
}

###
GET {{API_HostAddress}}/api/users/9a937bee-06f6-4f05-b486-6050965a105e
Accept: application/json

###
POST {{API_HostAddress}}/api/auth/send-code
Content-Type: application/json
{"phoneNumber": "89200600434" }

###
POST {{API_HostAddress}}/api/auth/verify-code
Content-Type: application/json
{"phoneNumber": "89200600434", "code": "2633" }