@API_HostAddress = https://localhost:7052

POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "phoneNumber": "89200730135",
  "name": "Виктор Баринов",
  "gender": "Male",
  "relationShip": "Serious",
  "dateOfBirth": "2015-05-14",
  "description": "Я повар из Клод Моне",
  "city": "Москва"
}

###

POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json
{
  "phoneNumber": "892000ва",
  "name": "1",
  "gender": "Female",
  "relationShip": "Serious",
  "dateOfBirth": "2001-05-15",
  "description": "Тестовое описание 2",
  "city": "Москва"
}

###

POST {{API_HostAddress}}/api/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjlkYWQwYi0wOGM4LTQ2YzgtODcxNS1lOTE4OThhYmMxZTAiLCJleHAiOjE3ODE4OTc1OTAsImlzcyI6IlZpYmVBcGkiLCJhdWQiOiJWaWJlQ2xpZW50In0.vJ_aAilqyJnMFOaJLlCtdk6GqVEyBn2OZzP12BxH4EA

{
  "fromUserId": "cb9dad0b-08c8-46c8-8715-e91898abc1e0",
  "toUserId": "cf82b549-ea1c-45db-b5da-04ec9135295d"
}

###
GET {{API_HostAddress}}/api/users/cb9dad0b-08c8-46c8-8715-e91898abc1e0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjlkYWQwYi0wOGM4LTQ2YzgtODcxNS1lOTE4OThhYmMxZTAiLCJleHAiOjE3ODE4OTc1OTAsImlzcyI6IlZpYmVBcGkiLCJhdWQiOiJWaWJlQ2xpZW50In0.vJ_aAilqyJnMFOaJLlCtdk6GqVEyBn2OZzP12BxH4EA
Accept: application/json

###
POST {{API_HostAddress}}/api/auth/send-code
Content-Type: application/json
{"phoneNumber": "89200000003" }

###
POST {{API_HostAddress}}/api/auth/verify-code
Content-Type: application/json
{"phoneNumber": "89200000003", "code": "7209" }